app/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from main.views import IndexPageView, ChangeLanguageView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', IndexPageView.as_view(), name='index'),

    path('i18n/', include('django.conf.urls.i18n')),
    path('language/', ChangeLanguageView.as_view(), name='change_language'),

    path('accounts/', include('accounts.urls')),
    path('vendor/', include('vendor.urls')),
    path('category/', include('category.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

category/urls.py
from django.urls import path
from . import views

# Application Name
app_name = 'category'

urlpatterns = [
    # Category List URL :
    path('', views.categoryListView, name = "category_list"),
    # Add Category URL :
    path('addcategory', views.categoryAddView, name = "category_add"),
    # Update Category URL :
    path('updatecategory/<int:id>', views.categoryUpdateView, name = "category_update"),
    # Delete Category URL :    
    path('deletecategory/<int:id>', views.categoryDeleteView, name = "category_delete"),
]

category/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length = 50, unique = True, blank = False)
    is_deleted = models.BooleanField(default = False)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    
    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        
    def __str__(self):
        return self.name

category/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Category
from . import constants

# Category List View :
def categoryListView(request):
    category = Category.objects.filter(is_deleted = 0)
    
    context = {
        'category'     : category,
        
        # Constant Rendering to Template. 
        'CATEGORY'     : constants.CategoryListConstants.CATEGORY,
        'TOTAL_VENDOR' : constants.CategoryListConstants.TOTAL_VENDOR,
        'ACTIVE'       : constants.CategoryListConstants.ACTIVE,
        'INACTIVE'     : constants.CategoryListConstants.INACTIVE,
        'ADD_CATEGORY' : constants.ADD_CATEGORY,
        'RESET'        : constants.CategoryListConstants.RESET,
        'ID'           : constants.CategoryListConstants.ID,
        'DATE_JOINED'  : constants.CategoryListConstants.DATE_JOINED,
        'CATEGORY_NAME': constants.CATEGORY_NAME,
        'ACTION'       : constants.CategoryListConstants.ACTION,
        'UPDATE'       : constants.CategoryListConstants.UPDATE,
        'DELETE'       : constants.CategoryListConstants.DELETE
    }
    
    return render(request, constants.categoryListURL, context) # Rendering to Category List.


# Category Add View :
def categoryAddView(request):
    if request.method == 'POST':
        category = request.POST['name'] 
            
        existing_category = Category.objects.filter(name = category, is_deleted = True).first()
        
        if existing_category:
            existing_category.is_deleted = False
            existing_category.save()
        else:
            category = Category.objects.create(name=category) 
        return redirect(constants.categoryListURLNAME)     # Redirect to Category List. 
    
    context = {
        # Constant Rendering to Template. 
        'ADD_CATEGORY'          : constants.ADD_CATEGORY,
        'CATEGORY_NAME'         : constants.CATEGORY_NAME,
        'CATEGORY_INFO_MESSAGE' : constants.CategoryAddConstants.CATEGORY_INFO_MESSAGE,
        'CANCEL'                : constants.CANCEL, 
    }

    return render(request, constants.addCategoryURL, context)  # Rendering to Add Category.


# Category Update View :
def categoryUpdateView(request, id):
    category = get_object_or_404(Category, pk = id)
    if request.method == "POST":
        category = Category.objects.update_or_create(
            pk = id,
            defaults = {
                "name": request.POST["name"],
            },
        )
        return redirect(constants.categoryListURLNAME)
    context = {
        'category'        : category,
        
        # Constant Rendering to Template. 
        'UPDATE_CATEGORY' : constants.CategoryUpdateConstants.UPDATE_CATEGORY,
        'CATEGORY_NAME'   : constants.CATEGORY_NAME,
        'CANCEL'          : constants.CANCEL, 
    }
    return render(request, constants.updateCategoryURL, context)   # Rendering to Update Category. 


# Category Delete View :
def categoryDeleteView(request, id):
    category = Category.objects.get(pk = id)
    category.is_deleted = True
    category.save()
    return redirect(constants.categoryListURLNAME)    # Redirect to Category List.

category/templates/add_Category.html
{% extends 'layouts/default/page.html' %}

{% load bootstrap4 %}
{% load i18n %}

<!-- Title -->
{% block title %} {% trans ADD_CATEGORY %} {% endblock %}

<!-- begin : Content -->
{% block content %}

    <!-- Heading -->
    <h4> {% trans ADD_CATEGORY %} </h4>
  
    <!-- begin : Form -->
    <form method="post">
        {% csrf_token %}
        <div class = "form-group">
            <label for = "name"> {% trans CATEGORY_NAME %} </label>
            <input type = "text" class = "form-control" name = "name" id = "name" placeholder = "Enter Category Name"  aria-describedby="name" required>
            <small id="name" class="form-text text-secondary"> {% trans CATEGORY_INFO_MESSAGE %} </small>
            <br>
            <button class = "btn btn-outline-primary"> {% trans ADD_CATEGORY %} </button>
            <a class = "btn btn-outline-primary ml-2" href = "{% url 'category:category_list' %}"> {% trans CANCEL %}</a>
        </div>
    </form>
    <!-- end : Form -->

{% endblock %}
<!-- end : Content -->

category/templates/category_list.html
{% extends 'layouts/default/page.html' %}

{% load bootstrap4 %}
{% load i18n %}

<!-- Title -->
{% block title %} {% trans CATEGORY %} {% endblock %}

<!-- begin : Content -->
{% block content %}
<section class="content">
    <div class="container"> 
        <div class = "row bg-dark mb-2">

            <!-- Total count of Category -->
            <div class = "d-flex justify-content col-sm-4 ml-4">
                <h3 class = "btn btn-secondary mt-2">{% trans TOTAL_VENDOR %}<h3> 
            </div>

             <!-- Category Heading at Top -->
            <div class = "d-flex justify-content-center col mt-2">
                <h2 class = "text-white"> {% trans CATEGORY %} </h2>
            </div>

            <div class = "d-flex justify-content-left col ml-6">
                <!-- Active count of Category -->
                <div class = "d-flex ml-5">
                    <h3 class = "btn btn-secondary mt-2">{% trans ACTIVE %}<h3> 
                </div>

                <!-- Inactive count of Category -->
                <div class = "d-flex ml-5">
                    <h3 class = "btn btn-secondary mt-2">{% trans INACTIVE %}<h3> 
                </div>
            </div>
        </div>

        <div class = "row mb-3">
            <div class = "d-flex justify-content-left col">

                <!-- Add Category Button at Top -->
                <a href = "{% url 'category:category_add' %}" class = "btn btn-outline-primary my-2 my-sm-0"> {% trans ADD_CATEGORY %} </a> 

                <!-- Reset Button at Top -->
                <a href = "{% url 'category:category_list' %}" class = "btn btn-outline-primary my-2 my-sm-0 ml-4"> {% trans RESET %} </a>
            </div>

            <div class = "d-flex justify-content-right col">

                <!-- Date Filter at Top -->
                <div class = "d-flex justify-content mr-2">
                    {% include "main/date_filter.html" %}
                </div>

                <!-- Search Bar at Top -->
                <div class = "d-flex justify-content ml-5">
                    {% include "main/search.html" %}
                </div>
            </div>
        </div>

        <div>
            <table class = "table table-sm table-bordered table-hover">

                <!-- Table Headers -->
                <thead class = "alert-warning">
                    <tr>
                        <th scope = "col"><center> {% trans  ID %} </th>
                        <th scope = "col"><center> {% trans DATE_JOINED %} </th>    
                        <th scope = "col"><center> {% trans CATEGORY_NAME %} </th>
                        <th scope = "col"><center> {% trans ACTION %} </th>
                    </tr>
                </thead>
                
                <!-- Table Data -->
                <tbody>
                {% for category in category  %}
                <tr>
                    <td><center>{{category.id}}</td>
                    <td><center>{{category.created_at.date}}    
                    <td><center>{{category.name}}</td>
                    <td>
                        <center>
                            <a class = "btn btn-outline-primary btn-sm" href = "{% url 'category:category_update' category.id %}">
                                <span class = "glyphicon glyphicon-edit"></span> {% trans UPDATE %} 
                            </a> 
                            <a class = "btn btn-outline-primary btn-sm" href = "{% url 'category:category_delete' category.id %}">
                                <span class = "glyphicon glyphicon-trash"></span> {% trans DELETE %}  
                            </a>
                        </center>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</section>
{% endblock %}
<!-- end : Content -->

category/templates/update_Category.html
{% extends 'layouts/default/page.html' %}

{% load bootstrap4 %}
{% load i18n %}

<!-- Title -->
{% block title %} {% trans UPDATE_CATEGORY %} {% endblock %}

<!-- begin : Content -->
{% block content %}

    <!-- Heading -->
    <h4> {% trans UPDATE_CATEGORY %} </h4>
  
    <!-- begin : Form -->
    <form method="post">
        {% csrf_token %}
        <div class = "form-group">
          <label for = "name"> {% trans CATEGORY_NAME %} </label>
          <input type = "text" class = "form-control" name = "name" id = "name" placeholder = "Enter Category Name"  aria-describedby="name" value = "{{category.name}}" required></input>
          <br>
          <button class = "btn btn-outline-primary"> {% trans UPDATE_CATEGORY %} </button>
          <a class = "btn btn-outline-primary ml-2" href = "{% url 'category:category_list' %}"> {% trans CANCEL %}</a>
        </div>
    </form>
    <!-- end : Form -->

{% endblock %}
<!-- end : Content -->